server:
  port: ${WEB_PORT:8078}
  error:
    whitelabel:
      enabled: false

spring:
  elasticsearch:
    uris: ${ELS_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding-model: text-embedding-3-small
  application:
    name: talkpick-backend
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  web:
    resources:
      add-mappings: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

host:
  name: ${HOST_NAME:http://localhost:3000}

#p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true

log:
  rolling:
    directory: logs
    file-name: talkpick-batch.log
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [TraceId: %X{traceId:-no-trace}] - %msg%n"
    max-history: 30
    total-size-cap: 10MB

jwt:
  secret: ${JWT_SECRET}
